export const OPCION_OTRA = '__OTRA__'

export const modelosPorMarca = {
  Toyota: [
    '4Runner',
    'Camry',
    'Corolla',
    'Highlander',
    'Hilux',
    'Land Cruiser',
    'Prado',
    'RAV4',
    'Tacoma',
    'Yaris',
  ],
  Honda: [
    'Accord',
    'Civic',
    'CR-V',
    'Fit',
    'HR-V',
    'Odyssey',
    'Passport',
    'Pilot',
  ],
  Hyundai: [
    'Accent',
    'Elantra',
    'Grand i10',
    'Kona',
    'Palisade',
    'Santa Fe',
    'Sonata',
    'Tucson',
  ],
  Kia: [
    'Carnival',
    'K5',
    'Picanto',
    'Rio',
    'Seltos',
    'Sorento',
    'Soul',
    'Sportage',
  ],
  Nissan: [
    'Altima',
    'Frontier',
    'Kicks',
    'Murano',
    'Pathfinder',
    'Sentra',
    'Versa',
    'X-Trail',
  ],
  Chevrolet: [
    'Camaro',
    'Captiva',
    'Colorado',
    'Equinox',
    'Silverado',
    'Suburban',
    'Tahoe',
    'Traverse',
  ],
  Ford: [
    'Bronco',
    'EcoSport',
    'Edge',
    'Escape',
    'Explorer',
    'F-150',
    'Maverick',
    'Ranger',
  ],
  Mazda: [
    'CX-3',
    'CX-30',
    'CX-5',
    'CX-50',
    'CX-9',
    'Mazda 2',
    'Mazda 3',
    'Mazda 6',
  ],
  Mitsubishi: [
    'ASX',
    'Eclipse Cross',
    'L200',
    'Mirage',
    'Montero',
    'Outlander',
    'Xpander',
  ],
  Suzuki: [
    'Baleno',
    'Celerio',
    'Ertiga',
    'Jimny',
    'S-Presso',
    'Swift',
    'Vitara',
  ],
  Volkswagen: [
    'Amarok',
    'Golf',
    'Jetta',
    'Passat',
    'Taos',
    'Tiguan',
    'Touareg',
  ],
  Jeep: [
    'Cherokee',
    'Compass',
    'Gladiator',
    'Grand Cherokee',
    'Renegade',
    'Wrangler',
  ],
  BMW: [
    'Serie 1',
    'Serie 3',
    'Serie 5',
    'X1',
    'X3',
    'X5',
    'X6',
  ],
  'Mercedes-Benz': [
    'Clase A',
    'Clase C',
    'Clase E',
    'GLA',
    'GLC',
    'GLE',
    'Sprinter',
  ],
  Audi: ['A3', 'A4', 'A5', 'A6', 'Q3', 'Q5', 'Q7'],
  Lexus: ['ES', 'GX', 'IS', 'NX', 'RX', 'UX'],
}

export const marcasVehiculo = Object.keys(modelosPorMarca)

export const coloresVehiculo = [
  'Blanco',
  'Negro',
  'Gris',
  'Plata',
  'Rojo',
  'Azul',
  'Verde',
  'Amarillo',
  'Marrón',
  'Beige',
  'Naranja',
  'Dorado',
]

const ultimoAnioModelo = new Date().getFullYear() + 1

export const aniosVehiculo = Array.from(
  { length: ultimoAnioModelo - 1980 + 1 },
  (_, indice) => ultimoAnioModelo - indice,
)