export const menuItems = [
  {
    label: 'Dashboard',
    path: '/app',
    description: 'Resumen operativo',
    group: 'Operación',
    roles: ['RECEPCION', 'TECNICO', 'CAJA', 'ADMINISTRACION'],
  },
  {
    label: 'Citas',
    path: '/app/citas',
    description: 'Agenda del taller',
    group: 'Operación',
    roles: ['RECEPCION', 'ADMINISTRACION'],
  },
  {
    label: 'Cotizaciones',
    path: '/app/cotizaciones',
    description: 'Propuestas comerciales',
    group: 'Operación',
    roles: ['RECEPCION', 'ADMINISTRACION'],
  },
  {
    label: 'Órdenes de Trabajo',
    path: '/app/ordenes-trabajo',
    description: 'Seguimiento de reparaciones',
    group: 'Operación',
    roles: ['RECEPCION', 'TECNICO', 'ADMINISTRACION'],
  },
  {
    label: 'Diagnósticos',
    path: '/app/diagnosticos',
    description: 'Evaluaciones de refrigeración',
    group: 'Operación',
    roles: ['TECNICO', 'ADMINISTRACION'],
  },
  {
    label: 'Clientes',
    path: '/app/clientes',
    description: 'Registro y consulta de clientes',
    group: 'Clientes',
    roles: ['RECEPCION', 'ADMINISTRACION'],
  },
  {
    label: 'Vehículos',
    path: '/app/vehiculos',
    description: 'Vehículos asociados a clientes',
    group: 'Clientes',
    roles: ['RECEPCION', 'TECNICO', 'ADMINISTRACION'],
  },
  {
    label: 'Historial Técnico',
    path: '/app/historial-tecnico',
    description: 'Servicios por vehículo',
    group: 'Clientes',
    roles: ['RECEPCION', 'TECNICO', 'ADMINISTRACION'],
  },
  {
    label: 'Inventario',
    path: '/app/inventario',
    description: 'Piezas, insumos y existencias',
    group: 'Inventario',
    roles: ['TECNICO', 'ADMINISTRACION'],
  },
  {
    label: 'Refrigerantes',
    path: '/app/refrigerantes',
    description: 'Control de recargas y consumo',
    group: 'Inventario',
    roles: ['TECNICO', 'ADMINISTRACION'],
  },
  {
    label: 'Servicios',
    path: '/app/servicios',
    description: 'Catálogo base de servicios',
    group: 'Inventario',
    roles: ['RECEPCION', 'TECNICO', 'ADMINISTRACION'],
  },
  {
    label: 'Facturación',
    path: '/app/facturacion',
    description: 'Facturas y pagos',
    group: 'Administración',
    roles: ['CAJA', 'ADMINISTRACION'],
  },
  {
    label: 'Reportes',
    path: '/app/reportes',
    description: 'Indicadores y reportes',
    group: 'Administración',
    roles: ['ADMINISTRACION'],
  },
  {
    label: 'Usuarios',
    path: '/app/usuarios',
    description: 'Equipo y permisos',
    group: 'Administración',
    roles: ['ADMINISTRACION'],
  },
]
